config/routes.rb
Parallax::Application.routes.draw do
  
  root :to => 'home#index'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  resources :admins
  resources :invite_admins
  resources :password_reset
  resources :links
  resources :books
  resources :photos

end

app/controllers/invite_admins_controller.rb
class InviteAdminsController < ApplicationController
  before_filter :require_login, :only => [:new, :create]
  
  def new
    @admin = Admin.new
  end
  
  def create
    if Admin.find_all_by_email(params[:admin][:email]).count < 1
      @admin = Admin.new(params[:admin])
      random_string = SecureRandom.base64(12)
      @admin.password = random_string
      @admin.password_confirmation = random_string
      @admin.activation_state = 'Invited'
      random_string2 = SecureRandom.base64(24)
      random_string2.gsub!('/', 's')
      @admin.activation_token = random_string2
      if @admin.save
        inviter = current_user
        AdminMailer.invite_admin_email(@admin, inviter).deliver
        redirect_to new_invite_admin_path, :notice => "#{t(:admin_invited)} #{@admin.email}"
      else
        redirect_to new_invite_admin_path, :notice => t(:invite_errors)
      end
    else
      redirect_to new_invite_admin_path, :notice => t(:already_has_account)
    end   
  end
  
  def edit
    #authorize! :update, @invite_admin
    @admin = Admin.find_by_activation_token(params[:id])
    not_authenticated unless @admin
  end
  
  def update
    #authorize! :update, @invite_admin
    @admin = Admin.find_by_activation_token(params[:admin][:activation_token])
    if @admin.update_attributes(params[:admin])
      @admin.activate!
      auto_login(@admin)
      redirect_to root_path, :notice => t(:account_created)
   else
     flash[:alert] = t(:failed_admin_creation)
     render :edit
   end
  end
end

app/views/invite_admins/edit.html.haml
#auth_wrapper
  .rdfrs_auth_form
    = simple_form_for @admin, :url => invite_admin_path(@admin), :method => :put do |f| 
      - if @admin.errors.any?
        %ul
          - @admin.errors.full_messages.each do |msg|
            %li= msg  
      = "Creating Account for: #{@admin.email}"
      = f.input :password, :class => 'pass_field', :placeholder => 'Password', :id => 'password'
      = f.input :password_confirmation, :class => 'pass_field', :placeholder => 'Password Confirmation', :id => 'password_confirmation'
      = f.input :activation_token, :value => @admin.activation_token, :as => :hidden
      = f.submit 'Create Account!', :class => 'button'

app/views/invite_admins/new.html.haml
%h2 Invite an Admin
= simple_form_for @admin, :url => invite_admins_path, :method => :post do |f|
  = f.input :email
  = f.submit