config/routes.rb
Parallax::Application.routes.draw do
  
  root :to => 'home#index'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  resources :admins
  resources :invite_admins
  resources :password_reset
  resources :links
  resources :books
  resources :photos

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :publisher_text, :publisher_url, :summary, :title, :cover
  
  has_attached_file :cover,
                    :styles => { :thumb => "100x129", :full => '330x427' },
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename"
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
  end
  
  def new
    @book = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to books_path, :notice => "Book created succesfully"
    else
      flash[:alert] = "Failed to create book"
      render :action => 'new'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    
    if @book.update_attributes(params[:book])
      redirect_to books_path, :notice => "Book Updated Succesfully"
    else
      flash[:alert] = "Failed to Update Book"
      render :action => 'edit'
    end
  end
  
  def destroy
    #todo write destroy stuff
  end
end

app/views/books/edit.html.haml
.book_edit_form
  = simple_form_for @book  do |f|
    = f.input :title
    = f.input :summary
    = f.input :description, :input_html => { :class => 'wysihtml5' }
    :javascript
      $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
      });
    = f.input :publisher_text
    = f.input :publisher_url
    = f.file_field :cover
    = f.button :submit

app/views/books/index.html.haml
= link_to "Create New Book", new_book_path if current_user
%br
- @books.each do |book|
  .book_banner= link_to image_tag( book.cover.url(:thumb)), book_path(book)
  .book_title= link_to book.title, book_path(book)
  %br

app/views/books/new.html.haml
.book_new_form
  = simple_form_for @book  do |f|
    = f.input :title, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.input :summary, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.input :description, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.input :publisher_text, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.input :publisher_url, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.file_field :cover, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.button :submit

app/views/books/show.html.haml
.show_book
  .book_title= @book.title if @book.title.present?
  .book_summary= @book.summary if @book.summary.present?
  .book_image= image_tag( @book.cover.url)
  .book_description= @book.description if @book.description.present?
  - if @book.publisher_text.present? && @book.publisher_url.present?
    .book_publisher= link_to( @book.publisher_text, @book.publisher_url)
  