config/routes.rb
Parallax::Application.routes.draw do
  
  root :to => 'home#index'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  resources :admins
  resources :invite_admins
  resources :password_reset
  resources :links
  resources :books
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :title, :image
  
  
  
  has_attached_file :image,
                    :styles => { :thumb => "100x100" },
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename"
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    @photos = Photo.all
  end
  
  def new
    @photo = Photo.new
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to photos_path, :notice => "Photo created succesfully"
    else
      flash[:alert] = "Failed to create photo"
      render :action => 'new'
    end
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    
    if @photo.update_attributes(params[:photo])
      redirect_to photos_path, :notice => "Photo Updated Succesfully"
    else
      flash[:alert] = "Failed to Update Photo"
      render :action => 'edit'
    end
  end
  
  def destroy
    #todo write destroy stuff
  end
end

app/views/photos/edit.html.haml
.photo_edit_form
  = simple_form_for @photo  do |f|
    = f.input :title, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.file_field :image, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
    = f.button :submit

app/views/photos/index.html.haml
= link_to "Create New Photo", new_photo_path if current_user
%br
- @photos.each do |photo|
  .photo_banner= link_to image_tag( photo.image.url(:thumb)), photo_path(photo)
  .photo_title= link_to photo.title, photo_path(photo)
  %br

app/views/photos/new.html.haml
.photo_new_form
= simple_form_for @photo  do |f|
  = f.input :title, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
  = f.file_field :image, :wrapper_html => { :class => 'input_div' }, :input_html => { :class => 'input_style' }
  = f.button :submit

app/views/photos/show.html.haml
.show_photo
  .photo_title= @photo.title if @photo.title.present?
  .photo_image= image_tag( @photo.image.url(:thumb))
  .photo_image= image_tag( @photo.image.url)

  