config/routes.rb
Parallax::Application.routes.draw do
  
  root :to => 'home#index'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  resources :admins
  resources :invite_admins
  resources :password_reset
  resources :links
  resources :books
  resources :photos

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    <link rel="shortcut icon" href="http://www.parallax-tripleephotography.com/indeximg/favicon.ico" >
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    = stylesheet_link_tag    "application"
    %title Parallax-Triple E
    <script language="JavaScript" type="text/JavaScript">
    <!--
    function MM_reloadPage(init) {  //reloads the window if Nav4 resized
    if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
    else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
    }
    MM_reloadPage(true);
    //-->
    </script>
%body#body
  .container
    .row.header
      .span12
        = link_to( image_tag('logo.jpg'), root_path) + image_tag('base.jpg')
    %br
    .row.nav
      .span3
        %nav
          %ul
            %li= link_to image_tag('gallery.jpg'), '#'
            %li= link_to image_tag('models.jpg'), '#'
            %li= link_to image_tag('books.jpg'), books_path
            %li= link_to image_tag('links.jpg'), links_path
            %li.text= link_to( "Logout", logout_path) if current_user
      .span9.content
        = yield
    .row
  .offset1.span10.footer
    = "#{mail_to  'ParallaxTripleE@aol.com', 'Contact Ed Emering', :target => '_blank'} Copyright ©2008 The Emering Companies, LLC".html_safe
  .google-analytics
    <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"> </script>
    <script type="text/javascript">
    _uacct = "UA-3717285-1";
    urchinTracker();
    </script>